# Etapa de construcción (Build)
FROM node:20-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa de producción (Servir con Nginx)
FROM nginx:alpine
# Copiamos los archivos compilados de Vite (carpeta dist) al servidor Nginx
COPY --from=build /app/dist /usr/share/nginx/html
# Exponemos el puerto 80 (el estándar web)
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]