# Etapa 1: Construcción (Build)
FROM node:22-bullseye-slim AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Compilamos el proyecto (Usa 'npm run build')
RUN npm run build

# Etapa 2: Servidor Web de Producción
FROM nginx:alpine
# IMPORTANTE: Si usas Vite, la carpeta generada es 'dist'. Si usaste Create React App, cambia 'dist' por 'build'.
COPY --from=build /app/dist /usr/share/nginx/html

# Exponemos el puerto 80 (el estándar web)
EXPOSE 80

# Iniciamos Nginx
CMD ["nginx", "-g", "daemon off;"]