version: '3.8'

services:
  # 1. Tu Base de Datos
  mongodb:
    image: mongo:latest
    container_name: rubik-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  # 2. Tu Servidor Node.js
  backend:
    build: ./backend
    container_name: rubik-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      # Sobrescribimos la variable para que se conecte al contenedor, no a localhost
      - MONGO_URI=mongodb://mongodb:27017/rubik_system
    restart: always

  # 3. Tu Interfaz React
  frontend:
    build: ./frontend
    container_name: rubik-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

# Definimos el volumen para que tus eventos de la BD no se borren si se apaga el servidor
volumes:
  mongo_data: