# Usamos una imagen ligera de Node.js (Bullseye evita errores con la librería serialport)
#FROM node:18-bullseye-slim
FROM node:18
# Creamos el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos primero los archivos de dependencias para aprovechar el caché de Docker
COPY package*.json ./

# Instalamos las dependencias
RUN npm install

# Copiamos el resto del código del backend
COPY . .

# Exponemos el puerto que usa tu Express
EXPOSE 5000

# Comando para iniciar el servidor
CMD ["node", "server.js"]
